### ISSUE TITLE
when build with ios7.1sdk has an error

### ISSUE THREAD

**Issue by louis-web** [ptoomey3/Keychain-Dumper#14]
I want to got the keys from iphone4/ios7.1. Do I need to do like this ?
set env:
`
ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk sdk
ln -s /Applications/Xcode.app/Contents/Developer toolchain

make
`

then, then result is:

`
In file included from main.m:31:
In file included from /work/Keychain-Dumper-master/sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:14:
In file included from /work/Keychain-Dumper-master/sdk/System/Library/Frameworks/UIKit.framework/Headers/UIActivityViewController.h:9:
In file included from /work/Keychain-Dumper-master/sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h:10:
In file included from /work/Keychain-Dumper-master/sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:13:
/work/Keychain-Dumper-master/sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDevice.h:33:1: error: 
      use of empty enum
};
^
main.m:318:2: error: selector element type 'id *' is not a valid object
        for (id *kSecClassType in (NSArray *) arguments) {
        ^    ~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [main.o] Error 1
`
